// Code generated by "stringer -type=Lang"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Golang-0]
	_ = x[Java-1]
	_ = x[CSharp-2]
	_ = x[C-3]
	_ = x[CPP-4]
}

const _Lang_name = "GolangJavaCSharpCCPP"

var _Lang_index = [...]uint8{0, 6, 10, 16, 17, 20}

func (i Lang) String() string {
	if i < 0 || i >= Lang(len(_Lang_index)-1) {
		return "Lang(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Lang_name[_Lang_index[i]:_Lang_index[i+1]]
}
